// Load quotes from localStorage or use default ones
// let quotes = JSON.parse(localStorage.getItem("quotes")) || [
//   { text: "Through hardship to the stars.", category: "Inspiration" },
//     { text: "Knowledge is power.", category: "School" },
//       { text: "Remember that you will die.", category: "Life" }
//       ];
//
//       // Save quotes to localStorage
//       function saveQuotes() {
//         localStorage.setItem("quotes", JSON.stringify(quotes));
//         }
//
//         // Show a random quote based on selected category
//         function showRandomQuote() {
//           const selectedCategory = document.getElementById("categoryFilter")?.value || "all";
//             const filteredQuotes = selectedCategory === "all"
//                 ? quotes
//                     : quotes.filter(q => q.category === selectedCategory);
//
//                       if (filteredQuotes.length === 0) {
//                           document.getElementById("quoteDisplay").innerHTML = "<p>No quotes in this category.</p>";
//                               return;
//                                 }
//
//                                   const randomQuote = filteredQuotes[Math.floor(Math.random() * filteredQuotes.length)];
//                                     document.getElementById("quoteDisplay").innerHTML = `
//                                         <blockquote>"${randomQuote.text}"</blockquote>
//                                             <p><strong>Category:</strong> ${randomQuote.category}</p>
//                                               `;
//
//                                                 sessionStorage.setItem("lastQuote", JSON.stringify(randomQuote));
//                                                 }
//
//                                                 // Add a new quote
//                                                 function addQuote() {
//                                                   const quoteText = document.getElementById("newQuoteText").value.trim();
//                                                     const quoteCategory = document.getElementById("newQuoteCategory").value.trim();
//
//                                                       if (quoteText && quoteCategory) {
//                                                           const newQuote = { text: quoteText, category: quoteCategory };
//                                                               quotes.push(newQuote);
//                                                                   saveQuotes();
//                                                                       populateCategories();
//                                                                           showRandomQuote();
//                                                                               document.getElementById("newQuoteText").value = "";
//                                                                                   document.getElementById("newQuoteCategory").value = "";
//                                                                                       postQuoteToServer(newQuote);
//                                                                                         } else {
//                                                                                             showNotification("Please enter both quote and category.");
//                                                                                               }
//                                                                                               }
//
//                                                                                               // Create input form for adding new quotes
//                                                                                               function createAddQuoteForm() {
//                                                                                                 const formContainer = document.createElement("div");
//
//                                                                                                   const quoteInput = document.createElement("input");
//                                                                                                     quoteInput.id = "newQuoteText";
//                                                                                                       quoteInput.placeholder = "Enter a new quote";
//
//                                                                                                         const categoryInput = document.createElement("input");
//                                                                                                           categoryInput.id = "newQuoteCategory";
//                                                                                                             categoryInput.placeholder = "Enter quote category";
//
//                                                                                                               const addButton = document.createElement("button");
//                                                                                                                 addButton.textContent = "Add Quote";
//                                                                                                                   addButton.addEventListener("click", addQuote);
//
//                                                                                                                     formContainer.appendChild(quoteInput);
//                                                                                                                       formContainer.appendChild(categoryInput);
//                                                                                                                         formContainer.appendChild(addButton);
//
//                                                                                                                           document.body.appendChild(formContainer);
//                                                                                                                           }
//
//                                                                                                                           // Populate category dropdown
//                                                                                                                           function populateCategories() {
//                                                                                                                             const categoryFilter = document.getElementById("categoryFilter");
//                                                                                                                               if (!categoryFilter) return;
//
//                                                                                                                                 const uniqueCategories = [...new Set(quotes.map(q => q.category))];
//                                                                                                                                   categoryFilter.innerHTML = '<option value="all">All Categories</option>';
//                                                                                                                                     uniqueCategories.forEach(category => {
//                                                                                                                                         const option = document.createElement("option");
//                                                                                                                                             option.value = category;
//                                                                                                                                                 option.textContent = category;
//                                                                                                                                                     categoryFilter.appendChild(option);
//                                                                                                                                                       });
//
//                                                                                                                                                         const savedCategory = localStorage.getItem("selectedCategory");
//                                                                                                                                                           if (savedCategory) {
//                                                                                                                                                               categoryFilter.value = savedCategory;
//                                                                                                                                                                 }
//                                                                                                                                                                 }
//
//                                                                                                                                                                 // Filter quotes based on selected category
//                                                                                                                                                                 function filterQuotes() {
//                                                                                                                                                                   const selectedCategory = document.getElementById("categoryFilter").value;
//                                                                                                                                                                     localStorage.setItem("selectedCategory", selectedCategory);
//                                                                                                                                                                       showRandomQuote();
//                                                                                                                                                                       }
//
//                                                                                                                                                                       // Export quotes as JSON file
//                                                                                                                                                                       function exportToJsonFile() {
//                                                                                                                                                                         const dataStr = JSON.stringify(quotes, null, 2);
//                                                                                                                                                                           const blob = new Blob([dataStr], { type: "application/json" });
//                                                                                                                                                                             const url = URL.createObjectURL(blob);
//
//                                                                                                                                                                               const a = document.createElement("a");
//                                                                                                                                                                                 a.href = url;
//                                                                                                                                                                                   a.download = "quotes.json";
//                                                                                                                                                                                     a.click();
//                                                                                                                                                                                       URL.revokeObjectURL(url);
//                                                                                                                                                                                       }
//
//                                                                                                                                                                                       // Import quotes from JSON file
//                                                                                                                                                                                       function importFromJsonFile(event) {
//                                                                                                                                                                                         const fileReader = new FileReader();
//                                                                                                                                                                                           fileReader.onload = function (e) {
//                                                                                                                                                                                               try {
//                                                                                                                                                                                                     const importedQuotes = JSON.parse(e.target.result);
//                                                                                                                                                                                                           if (Array.isArray(importedQuotes)) {
//                                                                                                                                                                                                                   quotes.push(...importedQuotes);
//                                                                                                                                                                                                                           saveQuotes();
//                                                                                                                                                                                                                                   populateCategories();
//                                                                                                                                                                                                                                           showRandomQuote();
//                                                                                                                                                                                                                                                   showNotification("Quotes imported successfully!");
//                                                                                                                                                                                                                                                         } else {
//                                                                                                                                                                                                                                                                 showNotification("Invalid JSON format.");
//                                                                                                                                                                                                                                                                       }
//                                                                                                                                                                                                                                                                           } catch {
//                                                                                                                                                                                                                                                                                 showNotification("Error reading file.");
//                                                                                                                                                                                                                                                                                     }
//                                                                                                                                                                                                                                                                                       };
//                                                                                                                                                                                                                                                                                         fileReader.readAsText(event.target.files[0]);
//                                                                                                                                                                                                                                                                                         }
//
//                                                                                                                                                                                                                                                                                         // Show notification in the UI
//                                                                                                                                                                                                                                                                                         function showNotification(message) {
//                                                                                                                                                                                                                                                                                           const notificationDiv = document.getElementById("notification");
//                                                                                                                                                                                                                                                                                             notificationDiv.textContent = message;
//                                                                                                                                                                                                                                                                                               notificationDiv.style.display = "block";
//                                                                                                                                                                                                                                                                                                 setTimeout(() => {
//                                                                                                                                                                                                                                                                                                     notificationDiv.textContent = "";
//                                                                                                                                                                                                                                                                                                         notificationDiv.style.display = "none";
//                                                                                                                                                                                                                                                                                                           }, 5000);
//                                                                                                                                                                                                                                                                                                           }
//
//                                                                                                                                                                                                                                                                                                           // Simulated server API
//                                                                                                                                                                                                                                                                                                           const mockApiUrl = "https://jsonplaceholder.typicode.com/posts";
//
//                                                                                                                                                                                                                                                                                                           // Post quote to server (simulated)
//                                                                                                                                                                                                                                                                                                           async function postQuoteToServer(quote) {
//                                                                                                                                                                                                                                                                                                             try {
//                                                                                                                                                                                                                                                                                                                 await fetch(mockApiUrl, {
//                                                                                                                                                                                                                                                                                                                       method: "POST",
//                                                                                                                                                                                                                                                                                                                             headers: { "Content-Type": "application/json" },
//                                                                                                                                                                                                                                                                                                                                   body: JSON.stringify(quote)
//                                                                                                                                                                                                                                                                                                                                       });
//                                                                                                                                                                                                                                                                                                                                         } catch (error) {
//                                                                                                                                                                                                                                                                                                                                             console.error("Error posting quote:", error);
//                                                                                                                                                                                                                                                                                                                                               }
//                                                                                                                                                                                                                                                                                                                                               }
//
//                                                                                                                                                                                                                                                                                                                                               // Simulate fetching server data
//                                                                                                                                                                                                                                                                                                                                               async function fetchQuotesFromServer() {
//                                                                                                                                                                                                                                                                                                                                                 return [
//                                                                                                                                                                                                                                                                                                                                                     { text: "Success is not final, failure is not fatal.", category: "Motivation" },
//                                                                                                                                                                                                                                                                                                                                                         { text: "The only way to do great work is to love what you do.", category: "Work" }
//                                                                                                                                                                                                                                                                                                                                                           ];
//                                                                                                                                                                                                                                                                                                                                                           }
//
//                                                                                                                                                                                                                                                                                                                                                           // Sync quotes with server
//                                                                                                                                                                                                                                                                                                                                                           async function syncQuotes() {
//                                                                                                                                                                                                                                                                                                                                                             const serverQuotes = await fetchQuotesFromServer();
//                                                                                                                                                                                                                                                                                                                                                               const localQuotes = JSON.parse(localStorage.getItem("quotes")) || [];
//
//                                                                                                                                                                                                                                                                                                                                                                 const isDifferent = JSON.stringify(localQuotes) !== JSON.stringify(serverQuotes);
//
//                                                                                                                                                                                                                                                                                                                                                                   if (isDifferent) {
//                                                                                                                                                                                                                                                                                                                                                                       localStorage.setItem("quotes", JSON.stringify(serverQuotes));
//                                                                                                                                                                                                                                                                                                                                                                           quotes = serverQuotes;
//                                                                                                                                                                                                                                                                                                                                                                               populateCategories();
//                                                                                                                                                                                                                                                                                                                                                                                   showRandomQuote();
//                                                                                                                                                                                                                                                                                                                                                                                       showNotification("Quotes updated from server. Conflicts resolved.");
//                                                                                                                                                                                                                                                                                                                                                                                         }
//                                                                                                                                                                                                                                                                                                                                                                                         }
//
//                                                                                                                                                                                                                                                                                                                                                                                         // Initialize everything
//                                                                                                                                                                                                                                                                                                                                                                                         document.getElementById("newQuote").addEventListener("click", showRandomQuote);
//                                                                                                                                                                                                                                                                                                                                                                                         document.getElementById("categoryFilter").addEventListener("change", filterQuotes);
//                                                                                                                                                                                                                                                                                                                                                                                         document.getElementById("exportBtn").addEventListener("click", exportToJsonFile);
//                                                                                                                                                                                                                                                                                                                                                                                         document.getElementById("importFile").addEventListener("change", importFromJsonFile);
//
//                                                                                                                                                                                                                                                                                                                                                                                         createAddQuoteForm();
//                                                                                                                                                                                                                                                                                                                                                                                         populateCategories();
//                                                                                                                                                                                                                                                                                                                                                                                         syncQuotes();
//
//                                                                                                                                                                                                                                                                                                                                                                                         // Show last quote or random quote on load
//                                                                                                                                                                                                                                                                                                                                                                                         const lastQuote = sessionStorage.getItem("lastQuote");
//                                                                                                                                                                                                                                                                                                                                                                                         if (lastQuote) {
//                                                                                                                                                                                                                                                                                                                                                                                           const quote = JSON.parse(lastQuote);
//                                                                                                                                                                                                                                                                                                                                                                                             document.getElementById("quoteDisplay").innerHTML = `
//                                                                                                                                                                                                                                                                                                                                                                                                 <blockquote>"${quote.text}"</blockquote>
//                                                                                                                                                                                                                                                                                                                                                                                                     <p><strong>Category:</strong> ${quote.category}</p>
//                                                                                                                                                                                                                                                                                                                                                                                                       `;
//                                                                                                                                                                                                                                                                                                                                                                                                       } else {
//                                                                                                                                                                                                                                                                                                                                                                                                         showRandomQuote();
//                                                                                                                                                                                                                                                                                                                                                                                                         }
//
//                                                                                                                                                                                                                                                                                                                                                                                                         // Periodic server sync
//                                                                                                                                                                                                                                                                                                                                                                                                         setInterval(syncQuotes, 30000);
//
